# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
stages:
  -test
  -build
  -deploy

test_job:
  stage: test
  script:
    -pytest

build_job:
  stage: build
  script:
    -docker compose up --build

deploy_job:
  stage: deploy
  script: