# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  python: circleci/python@2.1.1

name: CI

on :
  push :
    branches : master

jobs:
  test_and_linting:
    docker:
      - image: kevin976/circleci:latest
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Kmenguete/OpenClassrooms_project13/environment-variables
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: build docker image and run test and linting
          command: |
            docker build -t $IMAGE_NAME .
            flake8
            pytest
  publishLatestToHub:
    docker:
      - image: kevin976/circleci:latest
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Kmenguete/OpenClassrooms_project13/environment-variables
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: build docker image and push it to docker hub
          command: |
            docker build -t $IMAGE_NAME .
            docker push $IMAGE_NAME:latest

workflows:
  my_custom_workflow:
    jobs:
      - test_and_linting:
          context:
            -Docker login
            -Docker Hub repository
      - publishLatestToHub:
          context:
            -Docker login
            -Docker Hub repository
