# Generated by Django 4.1.7 on 2023-02-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelOptions(
                    name='address',
                    options={'verbose_name_plural': 'addresses'},
                ),
            ],
            # I am reusing an existing table, so I do nothing
            database_operations=[],
        ),
    ]
